### ISSUE TITLE
Is There Any Way to use `Promise.all` to Prevent Multiple Unnecessary Data Requests After 1 Fails?

### ISSUE THREAD

**Issue by manavm1990** [manavm1990/vuetify-dashboard#1]
[Here](https://github.com/manavm1990/vuetify-dashboard/blob/140d443dc7b23668da9c7a6513e0cf8feb5ce76b/src/views/Dashboard.vue#L59) I am using `Object.keys()` to dynamically populate `this.db`. 
However, if there is a problem requesting any one of the pieces of data, I would like to just abort subsequent calls. There is no need to keep getting the duplicated `error`(s).

It seems like `Promise.all()` would be the right fit...but unsure of how to combine that iteration with what I am already doing with `Object.keys()`.

**Comment by ricealexander** [comment]
If I'm reading this correctly, you make your requests in:

```javascript
Object.keys(this.db).map( /* map to requests here */ );
```

If the value of this were captured, I'd expect it to return an array of Promises

`Promise.all()`  expects an iterable containing promises, so my first thought would be to wrap it around what you already have. Would this work?

```javascript
Promise.all(
  Object.keys(this.db).map( /* map to requests here */ )
);
```

`Promise.all()` returns a single promise, so you can chain `.then`, `.catch`, and `.finally` to suit your needs.

**Comment by manavm1990** [comment]
Yeah, but then I have to _iterate_ over that _Array_ of _results_ and assign the right ones inside that _Object._ This is feasible, but a bit brittle. Probably not worth it...

**Comment by manavm1990** [comment]
https://github.com/manavm1990/vuetify-dashboard/commit/ae602df07d70e221cb8dfdb656d686bde1fb8725 🆗 This does a pretty good job. No excessive error logging at least - just 1 message. But, it will still make 4 `fetch`es...

**Comment by fauxsaurus** [comment]
@manavm1990 Something like [this](https://gist.github.com/minifyre/2c00f5080728c0913db12d4ed99cd520) (executes promises sequentially instead of all at once like `Promise.all`) could be modified into an [every](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/every) statement that would short circuit after any of the requests go wrong.

**Comment by manavm1990** [comment]
@minifyre But, firing off _requests_ sequentially means that I am taking more time for the successful _request_ instead of doing _asynchronously,_ right?

**Comment by fauxsaurus** [comment]
@manavm1990 While it is technically true that you could spend more time
sending requests one after another, I suspect the difference is negligible
(due to the browser's limit on how many concurrent requests you can send at
once).

Also, just to clarify, the code is still async. If you paste that gist in
Dev tools, you'll see console log requests a few seconds apart- so it's
still happening asyncly, they're just waiting for prior requests to finish,
at which point a modified code snippet could check if the others worked
before even trying.
